import Header from '~/components/Header';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'IMDb-CLONE',
    description: 'Generated by create next app to learn how IMDb app build',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Header />
                {/* header */}
                {/* Navbar */}
                {/* searchbar */}
                {children}
            </body>
        </html>
    );
}
